[package]
name = "task_list_manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

seafloor = {git = "https://github.com/zjhken/SeaFloor"}
chrono = "0.4.19"